### ISSUE TITLE
Cannot create Cloud Service

### ISSUE THREAD

**Issue by geertsmichael** [adobe/commerce-cif-connector#109]
### Expected Behaviour

I am following the step of the readme file to create a new cloud service.
I am expecting to have a working url in the documentation and I want to create a cloud service.

### Actual Behaviour

When visiting http://localhost:4502/libs/commerce/gui/content/configuration.html/conf I get a 404. And in the repository, I cannot find the following node either under /libs/commerce/gui/content/configuration

#### Steps to Reproduce

1. Go to http://localhost:4502/libs/commerce/gui/content/configuration.html/conf
2. Page doesn't work

#### Platform and Version

AEM 6.4.5 & CIF connector 0.9.0

**Comment by dplaton** [comment]
@geertsmichael This change will be released in 0.10.0 (due in a couple of days).

**Comment by geertsmichael** [comment]
I can create a cloud service now
