### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by dcuselton950** [adobe/commerce-cif-connector#11]
### Expected Behaviour
Use this as the POM file in my project and build using mvn clean install -PautoInstallAll .    just results in a connection error to cif-connector-all

#### Logs taken while reproducing problem

**Comment by mhaack** [comment]
@dcuselton950 can you please provide the error log? The build is working for many people and on CircleCI as well.

**Comment by dcuselton950** [comment]
Mark S in Aussie land helped me thru it .  ID10T error. I will close the issue.  Good to see the monitoring MH

**Comment by mhaack** [comment]
I'm interested in the log :-) if you still have it. The project build should be working without any Adobe internal dependencies, so everybody can easily build it.

**Comment by dcuselton950** [comment]
Just closed it….user error. Mark Szulc helped me………
