### ISSUE TITLE
GraphqlResourceProviderTest.testFactoryInitMethod fails on CentOS 7

### ISSUE THREAD

**Issue by dplaton** [adobe/commerce-cif-connector#112]
Hi,

I've got the same issue on the Centos 7.

Apache Maven 3.6.2 (40f52333136460af0dc0d7232c0dc0bcf0d9e117; 2019-08-27T15:06:16Z)
Maven home: /opt/apache-maven-3.6.2
Java version: 1.8.0_242, vendor: Oracle Corporation, runtime: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.242.b08-0.el7_7.x86_64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-957.12.2.el7.x86_64", arch: "amd64", family: "unix"

I've just tried to build the issues/cif-1336 and result is unfortunately the same.

Logs:
[ERROR] Failures: 
[ERROR]   GraphqlResourceProviderTest.testFactoryInitMethod:199 
resourceMapper.buildAllCategoryPaths();
Wanted 1 time:
-> at com.adobe.cq.commerce.graphql.resource.GraphqlResourceProviderTest.testFactoryInitMethod(GraphqlResourceProviderTest.java:199)
But was 2 times. Undesired invocation:
-> at com.adobe.cq.commerce.graphql.resource.GraphqlResourceProviderTest$2.run(GraphqlResourceProviderTest.java:179)

[INFO] 
[ERROR] Tests run: 110, Failures: 1, Errors: 0, Skipped: 0

...

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M4:test (default-test) on project cif-connector-graphql: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/aem/aem-projects/commerce-cif-connector/bundles/cif-connector-graphql/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M4:test (default-test) on project cif-connector-graphql: There are test failures.

Please refer to /home/aem/aem-projects/commerce-cif-connector/bundles/cif-connector-graphql/target/surefire-reports for the individual test results.
Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.

Regards,
Michael

_Originally posted by @abecek in https://github.com/adobe/commerce-cif-connector/issues/107#issuecomment-606293820_

**Comment by LSantha** [comment]
GraphqlResourceProviderTest.testFactoryInitMethod() was removed with commit https://github.com/adobe/commerce-cif-connector/commit/7143e033d8123d352aeab5330da47134d07563d4, so I'm closing this issue.
