### ISSUE TITLE
3rd party dependency coming from commerce-cif-connector is causing Quality code check from SonarQube (Cloud Manager) analysis to fail. 

### ISSUE THREAD

**Issue by losharma** [adobe/commerce-cif-connector#129]
For a customer, build on Adobe Cloud Manager is failing because of the code quality checks set in Cloud manager (SonarQube analysis).
Around 6000 issues are coming from commerce-cif-connector dependency that is adding nodes to the /libs node of AEM, which is conflicting below mentioned custom code quality rule.

Customer Packages Should Not Create or Modify Nodes Under /libs {#oakpal-customer-package}
Key: BannedPaths
Type: Bug
Severity: Blocker
 
Example issue from the analysis report:
imported path /libs/commerce/gui/components/common/cifpicker/clientlibs/cifpicker.js matches deny pattern /libs(/.*)?

Do we need any fixes from commerce-cif-connector side for this?

**Comment by mhaack** [comment]
@losharma this is know, for AMS customers using Adobe Cloud Manager the commerce-cif-connector must be installed by the AMS SRE. Please see https://github.com/adobe/commerce-cif-connector#installation

**Comment by losharma** [comment]
Thanks, @mhaack
