### ISSUE TITLE
Cannot select the root of the catalog

### ISSUE THREAD

**Issue by dcuselton950** [adobe/commerce-cif-connector#15]
### Expected Behaviour
When you bind the root catalog, it will allow you to select the root catalog to render from the top of the catalog in the menu

### Actual Behaviour

You cannot select the top of the catalog to render, you have to pick one of the top level leafs of the hierachy.

#### Steps to Reproduce

below is image where you can see the root of the catalog, but you are not allowed to select it. 

![Unknown](https://user-images.githubusercontent.com/19351790/57863626-47da9400-77af-11e9-968f-d0f4a113a40b.png)

If you do select it, instead of being able to just stop there, you have to choose one of the sub-categories. 

![Unknown-1](https://user-images.githubusercontent.com/19351790/57863687-617bdb80-77af-11e9-9338-ab38603959f8.png)

#### Logs taken while reproducing problem

**Comment by LSantha** [comment]
Thank you, @dcuselton950. We are aware of this issue and will work on it.

**Comment by LSantha** [comment]
@dcuselton950 , a solution for this issue was merged to master branch.
Could you please check if it works for you?

**Comment by mhaack** [comment]
@LSantha @dcuselton950 I verified that fix, works now if you use the snapshot version from the master branch, will be included in next release.

**Comment by dcuselton950** [comment]
Thanks Markus
