### ISSUE TITLE
Version Issue with commerce-cif-graphql-client

### ISSUE THREAD

**Issue by chetanyajain** [adobe/commerce-cif-connector#161]
The latest version (1.6) of cif-connector embeds the 1.6.0 version of commerce-cif-graphql-client. 

However, the latest version of cif-components (https://github.com/adobe/aem-core-cif-components) expects a 1.7 version and this keeps the bundle in the installed state.

We have to manually upload the latest version of graphql-client (1.7) to resolve this. Can the cif-connector export the 1.7 version of graphql-client please so that we don't have to add the extra step?

**Comment by herzog31** [comment]
This was fixed by #162 and is available in the [cif-connector-reactor-1.7.0](https://github.com/adobe/commerce-cif-connector/releases/tag/cif-connector-reactor-1.7.0) release.
