### ISSUE TITLE
JS Error after Binding product (Read me doc 3rd step in CIF Magento GraphQL Configuration)

### ISSUE THREAD

**Issue by Bhargav411** [adobe/commerce-cif-connector#20]
Followed the Read me document.

Installed connector and configured on AEM 6.5.

After I clicked on 'Bind products', getting console error and displaying blank page.

The console error says -" Uncaught TypeError: Cannot read property 'dataset' of undefined" in foundation.js

<img width="1647" alt="Screen Shot 2019-05-20 at 12 41 44 pm" src="https://user-images.githubusercontent.com/22632630/57995899-d892d600-7b07-11e9-8045-94de5f0f9f62.png">

@LSantha

**Comment by herzog31** [comment]
Please stick to the issue template.

Are there any entries in the AEM `error.log` you can provide?

**Comment by Bhargav411** [comment]
Attached the error trace found in AEM error logs.


[error-log.txt](https://github.com/adobe/commerce-cif-connector/files/3197455/error-log.txt)

**Comment by herzog31** [comment]
It looks like that in your configuration you use an `http://` endpoint to point to your Magento instance. This is **not** supported. Please use `https://`. If your instance doesn't have a proper TLS certificate configured, you can activate the `Accept self-signed SSL certificates` option.

**Comment by Bhargav411** [comment]
@herzog31 Enabled and that resolved all above errors. Thanks
