### ISSUE TITLE
CIF Catalog Magento GraphQL Configuration Factory missing

### ISSUE THREAD

**Issue by the-dugi** [adobe/commerce-cif-connector#21]
### Expected Behaviour
In the AEM Web console - configuration we should be able to locate CIF Catalog Magento GraphQL Configuration Factory and create a child configuration

### Actual Behaviour
In the AEM Web console - configuration the CIF Catalog Magento GraphQL Configuration Factory is missing.

### Reproduce Scenario (including but not limited to)
After pulling the latest version from the master brunch and installing the package on AEM the  CIF Catalog Magento GraphQL Configuration Factory is missing.

![issue](https://user-images.githubusercontent.com/46922736/58046950-1400c500-7b47-11e9-86dc-ce9214a9ebd6.png)

#### Platform and Version
AEM 6.5 

#### Logs taken while reproducing problem

**Comment by Bhargav411** [comment]
If you build the package from 'all' folder then you can see the above behavior. But if you build it from root pom then you can see catalog magento factory in console.. Looks like 'all' doesn't have this.

**Comment by mhaack** [comment]
@the-dugi I can confirm this behavior and we will provide a fix for that. You can install everything using  `mvn clean install -PautoInstall` like described in the readme.md as a workaround.

**Comment by mhaack** [comment]
Fixed. This was related to an outdated dependency in the `all` package which is updated now. Just get and build the latest from git or download the all package from Maven Central.
