### ISSUE TITLE
Binding not working as expected

### ISSUE THREAD

**Issue by robertymb** [adobe/commerce-cif-connector#43]
### Expected Behaviour
After binding product catalog to AEM resource tree expected to see categories and products list.

### Actual Behaviour
After binding product catalog to AEM resource tree *cannot* see categories and products list.
![Screenshot from 2019-08-21 15-40-53](https://user-images.githubusercontent.com/4612887/63460834-b0c84c80-c42d-11e9-98f1-724b1524d49e.png)

#### Steps to Reproduce
Follow README.md tutorial until step 3;

#### Platform and Version
AEM 6.4.4 
Magento 2.3.2
commerce-cif-connector 0.4.0

#### Sample Code that illustrates the problem
N/A

#### Logs taken while reproducing problem
Just deleted the bind called `magentodemo` and create a new one called `magentodemo2`. Logs doesn't seems to have further details.

`error.log`
```
21.08.2019 19:02:17.118 *INFO* [sling-threadpool-cda251d5-39bd-4243-9783-56b79f16384b-(apache-sling-job-thread-pool)-11-com_day_cq_replication_job_publish-2(com/day/cq/replication/job/publish-2)] com.day.cq.replication.Agent.publish-2 <<
21.08.2019 19:02:17.118 *INFO* [sling-threadpool-cda251d5-39bd-4243-9783-56b79f16384b-(apache-sling-job-thread-pool)-11-com_day_cq_replication_job_publish-2(com/day/cq/replication/job/publish-2)] com.day.cq.replication.Agent.publish-2 << ReplicationAction DELETE ok.
21.08.2019 19:02:17.118 *INFO* [sling-threadpool-cda251d5-39bd-4243-9783-56b79f16384b-(apache-sling-job-thread-pool)-11-com_day_cq_replication_job_publish-2(com/day/cq/replication/job/publish-2)] com.day.cq.replication.Agent.publish-2 Message sent.
21.08.2019 19:02:17.118 *INFO* [sling-threadpool-cda251d5-39bd-4243-9783-56b79f16384b-(apache-sling-job-thread-pool)-11-com_day_cq_replication_job_publish-2(com/day/cq/replication/job/publish-2)] com.day.cq.replication.Agent.publish-2 ------------------------------------------------
21.08.2019 19:02:17.118 *INFO* [sling-threadpool-cda251d5-39bd-4243-9783-56b79f16384b-(apache-sling-job-thread-pool)-11-com_day_cq_replication_job_publish-2(com/day/cq/replication/job/publish-2)] com.day.cq.replication.Agent.publish-2 Replication (DELETE) of /etc/commerce/products/magentodemo successful.
21.08.2019 19:02:17.118 *INFO* [sling-threadpool-cda251d5-39bd-4243-9783-56b79f16384b-(apache-sling-job-thread-pool)-11-com_day_cq_replication_job_publish-2(com/day/cq/replication/job/publish-2)] com.day.cq.replication.Agent.publish-2.queue Job for agent publish-2 processed in 64ms. Ok.
21.08.2019 19:02:20.004 *INFO* [CommitStats] CommitStats 19 commits by 4 users [78% sling-event, 10% audit-service, 5% replication-service, 5% admin] from 4 locations [57% HTTP-POST:/bin/wcmcommand, 15% threadpool:o.a.jackrabbit.oak.spi.commit.BackgroundObser..., 15% jobmanager:job.finishJob, 10% scheduled:replication-audit] (4 types [57% HTTP-POST, 15% jobmanager, 15% threadpool, 10% scheduled]) [CommitStats overhead was 3ms = 158.0us / commit]
21.08.2019 19:02:20.859 *INFO* [oak-lucene-102] org.apache.jackrabbit.oak.plugins.blob.AbstractSharedCachingDataStore Added blob [04300bb055785ade665c44ea141359bf1ec4703a8be19d0d2f05ee220a051941] to backend
21.08.2019 19:02:21.082 *INFO* [oak-lucene-102] org.apache.jackrabbit.oak.plugins.blob.AbstractSharedCachingDataStore Added blob [63e4eed3d9318419d545d1eeddfb29129144b41da4dd9a6f1a4c63affbb09061] to backend
21.08.2019 19:02:21.261 *INFO* [oak-lucene-102] org.apache.jackrabbit.oak.plugins.blob.AbstractSharedCachingDataStore Added blob [c1da90c66c68537eb6b04d506268b6b4a821c5e95a655b31e153503560d78901] to backend
```

**Comment by mhaack** [comment]
@robertymb can you dump your OSGI configuration of the backend connection here to validate?

Also please create a separate log with `cif-connector-graphql` and `com.adobe.cq.commerce.virtual` set to debug, that should give more details.

**Comment by robertymb** [comment]
Hey @mhaack,

Sorry delay, I was having a lot of trouble to logging since it seems to not logging anything after binding.

I tried to created a separated log for `cif-connector-graphql` and `com.adobe.cq.commerce.virtual` but it seems it's not logging after binding. It logs only when AEM starts (see screenshots below). Whatever, I have logged information from `com.adobe.cq.commerce.*`. Got a interesting log anyway: `com.adobe.cq.commerce.impl.CommerceAdapterFactory Unable to adapt resource to type com.adobe.cq.commerce.api.Product`

Logs after binding:
![Selection_015](https://user-images.githubusercontent.com/4612887/63777781-16975700-c8ba-11e9-86b2-535ed8a53c36.png)
```
=> access.log <==
187.19.15.35 - admin 27/Aug/2019:13:55:25 +0000 "POST /etc/commerce/products/ HTTP/1.1" 201 2593 "http://<ofuscated url>/mnt/overlay/commerce/gui/content/products/bindproducttreewizard.html/etc/commerce/products/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36"
187.19.15.35 - admin 27/Aug/2019:13:55:25 +0000 "POST /etc/commerce/products/ HTTP/1.1" 201 2593 "http://<ofuscated url>/mnt/overlay/commerce/gui/content/products/bindproducttreewizard.html/etc/commerce/products/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36"

==> com.adobe.cq.commerce.log <==
27.08.2019 13:55:25.615 *DEBUG* [187.19.15.35 [1566914125612] POST /etc/commerce/products/ HTTP/1.1] com.adobe.cq.commerce.pim.impl.PIMPostProcessor post-processing modification to /etc/commerce/products/magento2
27.08.2019 13:55:25.626 *DEBUG* [187.19.15.35 [1566914125611] POST /etc/commerce/products/ HTTP/1.1] com.adobe.cq.commerce.pim.impl.PIMPostProcessor post-processing modification to /etc/commerce/products/magento2
27.08.2019 13:55:25.853 *DEBUG* [187.19.15.35 [1566914125827] GET /libs/commerce/gui/content/products.html/etc/commerce/products HTTP/1.1] com.adobe.cq.commerce.impl.CommerceAdapterFactory Unable to adapt resource to type com.adobe.cq.commerce.api.Product
27.08.2019 13:55:25.853 *DEBUG* [187.19.15.35 [1566914125827] GET /libs/commerce/gui/content/products.html/etc/commerce/products HTTP/1.1] com.adobe.cq.commerce.impl.CommerceAdapterFactory Unable to adapt resource to type com.adobe.cq.commerce.api.Product
27.08.2019 13:55:25.853 *DEBUG* [187.19.15.35 [1566914125827] GET /libs/commerce/gui/content/products.html/etc/commerce/products HTTP/1.1] com.adobe.cq.commerce.impl.CommerceAdapterFactory Unable to adapt resource to type com.adobe.cq.commerce.api.Product
27.08.2019 13:55:25.854 *DEBUG* [187.19.15.35 [1566914125827] GET /libs/commerce/gui/content/products.html/etc/commerce/products HTTP/1.1] com.adobe.cq.commerce.impl.CommerceAdapterFactory Unable to adapt resource to type com.adobe.cq.commerce.api.Product

==> request.log <==
27/Aug/2019:13:55:25 +0000 [2983] -> POST /etc/commerce/products/ HTTP/1.1
27/Aug/2019:13:55:25 +0000 [2984] -> POST /etc/commerce/products/ HTTP/1.1
27/Aug/2019:13:55:25 +0000 [2984] <- 201 text/html 13ms
27/Aug/2019:13:55:25 +0000 [2983] <- 201 text/html 20ms
27/Aug/2019:13:55:25 +0000 [2985] -> GET /libs/commerce/gui/content/products.html/etc/commerce/products HTTP/1.1

==> access.log <==
187.19.15.35 - admin 27/Aug/2019:13:55:25 +0000 "GET /libs/commerce/gui/content/products.html/etc/commerce/products HTTP/1.1" 200 41764 "http://<ofuscated url>/mnt/overlay/commerce/gui/content/products/bindproducttreewizard.html/etc/commerce/products/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36"
187.19.15.35 - admin 27/Aug/2019:13:55:26 +0000 "GET /libs/granite/csrf/token.json HTTP/1.1" 200 103 "http://<ofuscated url>/libs/commerce/gui/content/products.html/etc/commerce/products" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36"
187.19.15.35 - admin 27/Aug/2019:13:55:26 +0000 "GET /libs/cq/i18n/dict.en.json HTTP/1.1" 304 - "http://<ofuscated url>/libs/commerce/gui/content/products.html/etc/commerce/products" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36"

==> request.log <==
27/Aug/2019:13:55:25 +0000 [2985] <- 200 text/html;charset=utf-8 55ms
27/Aug/2019:13:55:26 +0000 [2986] -> GET /libs/granite/csrf/token.json HTTP/1.1
27/Aug/2019:13:55:26 +0000 [2986] <- 200 application/json 2ms
27/Aug/2019:13:55:26 +0000 [2987] -> GET /libs/cq/i18n/dict.en.json HTTP/1.1
27/Aug/2019:13:55:26 +0000 [2987] <- 304 - 1ms

==> access.log <==
187.19.15.35 - admin 27/Aug/2019:13:55:27 +0000 "GET /libs/cq/security/userinfo.json?cq_ck=1566914127020 HTTP/1.1" 200 1917 "http://<ofuscated url>/libs/commerce/gui/content/products.html/etc/commerce/products" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36"
187.19.15.35 - admin 27/Aug/2019:13:55:27 +0000 "GET /bin/acs-commons/dynamic-classicui-clientlibs.json?_dc=1566914127335 HTTP/1.1" 200 139 "http://<ofuscated url>/libs/commerce/gui/content/products.html/etc/commerce/products" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36"
187.19.15.35 - admin 27/Aug/2019:13:55:27 +0000 "GET /mnt/overlay/granite/ui/content/shell/header/actions/pulse.data.json?_=1566914126127 HTTP/1.1" 200 1527 "http://<ofuscated url>/libs/commerce/gui/content/products.html/etc/commerce/products" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36"
187.19.15.35 - admin 27/Aug/2019:13:55:27 +0000 "GET /mnt/overlay/granite/ui/content/tree.0.html/etc/commerce/products?columnPath=/mnt/overlay/commerce/gui/content/products/jcr%3acontent/views/column&_=1566914127508 HTTP/1.1" 200 181 "http://<ofuscated url>/libs/commerce/gui/content/products.html/etc/commerce/products" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36"

==> com.adobe.cq.commerce.log <==
27.08.2019 13:55:27.577 *DEBUG* [187.19.15.35 [1566914127570] GET /mnt/overlay/granite/ui/content/tree.0.html/etc/commerce/products HTTP/1.1] com.adobe.cq.commerce.impl.CommerceAdapterFactory Unable to adapt resource to type com.adobe.cq.commerce.api.Product
27.08.2019 13:55:27.577 *DEBUG* [187.19.15.35 [1566914127570] GET /mnt/overlay/granite/ui/content/tree.0.html/etc/commerce/products HTTP/1.1] com.adobe.cq.commerce.impl.CommerceAdapterFactory Unable to adapt resource to type com.adobe.cq.commerce.api.Product

==> request.log <==
27/Aug/2019:13:55:27 +0000 [2988] -> GET /libs/cq/security/userinfo.json?cq_ck=1566914127020 HTTP/1.1
27/Aug/2019:13:55:27 +0000 [2988] <- 200 application/json 2ms
27/Aug/2019:13:55:27 +0000 [2989] -> GET /bin/acs-commons/dynamic-classicui-clientlibs.json?_dc=1566914127335 HTTP/1.1
27/Aug/2019:13:55:27 +0000 [2989] <- 200 application/json 1ms
27/Aug/2019:13:55:27 +0000 [2990] -> GET /mnt/overlay/granite/ui/content/shell/header/actions/pulse.data.json?_=1566914126127 HTTP/1.1
27/Aug/2019:13:55:27 +0000 [2990] <- 200 application/json 24ms
27/Aug/2019:13:55:27 +0000 [2991] -> GET /mnt/overlay/granite/ui/content/tree.0.html/etc/commerce/products?columnPath=/mnt/overlay/commerce/gui/content/products/jcr%3acontent/views/column&_=1566914127508 HTTP/1.1
27/Aug/2019:13:55:27 +0000 [2991] <- 200 application/json 8ms
```

OSGI Config:
![Selection_009](https://user-images.githubusercontent.com/4612887/63777942-59f1c580-c8ba-11e9-9ee7-5d0feb4a105f.png)
![Selection_010](https://user-images.githubusercontent.com/4612887/63777946-5b22f280-c8ba-11e9-8952-29eef2ff3aa4.png)

OSGI Version:
![Selection_013](https://user-images.githubusercontent.com/4612887/63777967-6413c400-c8ba-11e9-8801-157029daee43.png)
![Selection_012](https://user-images.githubusercontent.com/4612887/63777968-64ac5a80-c8ba-11e9-9d7a-d097c787b032.png)
![Selection_011](https://user-images.githubusercontent.com/4612887/63777969-64ac5a80-c8ba-11e9-8c38-a7912364b1b4.png)

Log Config:
![Selection_003](https://user-images.githubusercontent.com/4612887/63777688-e64fb880-c8b9-11e9-9af4-7d17b0ac13c3.png)
![Selection_005](https://user-images.githubusercontent.com/4612887/63777712-f1a2e400-c8b9-11e9-93b3-7af4f64347ea.png)
![Selection_014](https://user-images.githubusercontent.com/4612887/63777740-ff586980-c8b9-11e9-8b2b-9de7e8167e2e.png)

Logging connector after it starts:
```
==> cif-connector-graphql.log <==
27.08.2019 10:18:39.874 *INFO* [FelixStartLevel] com.adobe.commerce.cif.connector-graphql Service [3537, [org.osgi.service.cm.ManagedService]] ServiceEvent REGISTERED
27.08.2019 10:18:39.879 *INFO* [FelixStartLevel] com.adobe.commerce.cif.connector-graphql Service [CIFProductFieldChildrenDataSourceServlet,3538, [javax.servlet.Servlet]] ServiceEvent REGISTERED
27.08.2019 10:18:39.892 *INFO* [FelixStartLevel] com.adobe.commerce.cif.connector-graphql BundleEvent STARTED
27.08.2019 10:18:40.096 *INFO* [FelixStartLevel] com.adobe.commerce.cif.connector-graphql Service [com.adobe.cq.commerce.graphql.resource.GraphqlResourceProviderFactory,3570, [com.adobe.cq.commerce.virtual.catalog.data.CatalogDataResourceProviderFactory, com.adobe.cq.commerce.virtual.catalog.data.CatalogIdentifier]] ServiceEvent REGISTERED
27.08.2019 10:18:40.098 *INFO* [FelixStartLevel] com.adobe.commerce.cif.connector-graphql Service [com.adobe.cq.commerce.graphql.magento.GraphqlDataServiceImpl.8322faf3-ed94-4a32-adaa-47d9e06abb2a,3569, [com.adobe.cq.commerce.graphql.magento.GraphqlDataService]] ServiceEvent REGISTERED
27.08.2019 10:19:02.085 *INFO* [Apache Sling Repository Startup Thread] com.adobe.commerce.cif.connector-graphql Service [ServletResourceProvider for Servlets at [/libs/foundation/components/primary/commerce/gui/components/common/cifproductfield/datasources/children/GET.servlet],5251, [org.apache.sling.spi.resource.provider.ResourceProvider]] ServiceEvent REGISTERED
27.08.2019 10:19:36.973 *INFO* [Apache Sling Repository Startup Thread] com.adobe.commerce.cif.connector-graphql Service [ServletResourceProvider for Servlets at [/bin/wcm/contentfinder/cifproduct/view.servlet, /bin/wcm/contentfinder/cifproduct/view],8098, [org.apache.sling.spi.resource.provider.ResourceProvider]] ServiceEvent REGISTERED
27.08.2019 10:19:36.992 *INFO* [Apache Sling Repository Startup Thread] com.adobe.commerce.cif.connector-graphql Service [ServletResourceProvider for Servlets at [/bin/wcm/contentfinder/cifproduct/view.servlet, /bin/wcm/contentfinder/cifproduct/view],8099, [org.apache.sling.spi.resource.provider.ResourceProvider]] ServiceEvent REGISTERED
27.08.2019 10:19:36.994 *INFO* [Apache Sling Repository Startup Thread] com.adobe.commerce.cif.connector-graphql Service [GraphqlProductViewHandler,8097, [javax.servlet.Servlet]] ServiceEvent REGISTERED
27.08.2019 10:19:36.998 *INFO* [Apache Sling Repository Startup Thread] com.adobe.commerce.cif.connector-graphql Service [com.adobe.cq.commerce.omnisearch.ProductsSuggestionOmniSearchHandler,8113, [com.adobe.granite.omnisearch.spi.core.OmniSearchHandler]] ServiceEvent REGISTERED

==> com.adobe.cq.commerce.virtual.log <==
27.08.2019 10:18:39.856 *INFO* [FelixStartLevel] com.adobe.commerce.cif.virtual-catalog BundleEvent RESOLVED
27.08.2019 10:18:39.893 *INFO* [FelixStartLevel] com.adobe.commerce.cif.virtual-catalog BundleEvent STARTING
27.08.2019 10:18:39.897 *INFO* [FelixStartLevel] com.adobe.commerce.cif.virtual-catalog Service [com.adobe.cq.commerce.virtual.catalog.admin.impl.CatalogIdentifierDatasource,3539, [javax.servlet.Servlet]] ServiceEvent REGISTERED
27.08.2019 10:18:39.900 *ERROR* [FelixStartLevel] com.adobe.commerce.cif.virtual-catalog bundle com.adobe.commerce.cif.virtual-catalog:0.1.0 (672)[com.adobe.cq.commerce.virtual.catalog.admin.impl.CatalogIdentifierDatasource(3421)] : Field catalogIdentifierService in class class com.adobe.cq.commerce.virtual.catalog.admin.impl.CatalogIdentifierDatasource must be declared volatile to handle a dynamic reference
27.08.2019 10:18:39.903 *INFO* [FelixStartLevel] com.adobe.commerce.cif.virtual-catalog BundleEvent STARTED
27.08.2019 10:18:40.095 *INFO* [FelixStartLevel] com.adobe.commerce.cif.virtual-catalog Service [com.adobe.cq.commerce.virtual.catalog.data.impl.CatalogIdentifierServiceImpl,3571, [com.adobe.cq.commerce.virtual.catalog.data.CatalogIdentifierService]] ServiceEvent REGISTERED
27.08.2019 10:19:02.095 *INFO* [Apache Sling Repository Startup Thread] com.adobe.commerce.cif.virtual-catalog Service [ServletResourceProvider for Servlets at [/libs/foundation/components/primary/commerce/gui/components/admin/products/bindproducttreewizard/catalogidentifierdatasource/HEAD.servlet, /libs/foundation/components/primary/commerce/gui/components/admin/products/bindproducttreewizard/catalogidentifierdatasource/GET.servlet],5252, [org.apache.sling.spi.resource.provider.ResourceProvider]] ServiceEvent REGISTERED
27.08.2019 10:19:02.104 *INFO* [Apache Sling Repository Startup Thread] com.adobe.commerce.cif.virtual-catalog Service [ServletResourceProvider for Servlets at [/libs/foundation/components/primary/commerce/gui/components/admin/products/bindproducttreewizard/catalogidentifierdatasource/HEAD.servlet, /libs/foundation/components/primary/commerce/gui/components/admin/products/bindproducttreewizard/catalogidentifierdatasource/GET.servlet],5253, [org.apache.sling.spi.resource.provider.ResourceProvider]] ServiceEvent REGISTERED
27.08.2019 10:19:04.882 *INFO* [Apache Sling Repository Startup Thread] com.adobe.commerce.cif.virtual-catalog Service [com.adobe.cq.commerce.virtual.catalog.data.impl.CatalogDataResourceProviderManagerImpl,5497, [com.adobe.cq.commerce.virtual.catalog.data.CatalogDataResourceProviderManager]] ServiceEvent REGISTERED
```

Let me know if you need more information.

Thanks,

**Comment by mhaack** [comment]
I can unfortunately not reproduce this behaviour, especially when you don't get any errors.

Lets check if the binding is created correctly and the underlying services are created. Can you please share the properties for `/var/commerce/products/magento2` (the root folder of the binding) from CRXDE.

Also when creating a new binding you should see a message like:
```
29.08.2019 14:08:05.117 *INFO* [sling-oak-observation-13] com.adobe.commerce.cif.virtual-catalog Service [Provider of virtual catalog data resources,8285, [org.apache.sling.spi.resource.provider.ResourceProvider]] ServiceEvent REGISTERED
```

Also please check if the OSGI services are loaded via http://localhost:4502/system/console/bundles console. Look for the `CIF Virtual Catalog - Bundle` bundle and open details. You should see a service like

<img width="1216" alt="Screenshot 2019-08-29 at 14 16 49" src="https://user-images.githubusercontent.com/2643450/63939500-b7774500-ca67-11e9-8f6d-5e4e085d29ec.png">

There must be one of these for each binding you create in the products console.

**Comment by robertymb** [comment]
One insight: Can this problem be related with Javascript or compressor? We had to change YUI compressor to GCC compressor since it wasn't working before. That's the only thing we changed.

You're right, logs doesn't seems enough. Not sure what that means:

```
com.adobe.cq.commerce.impl.CommerceAdapterFactory Unable to adapt resource to type com.adobe.cq.commerce.api.Product
```

Nothing related with com.adobe.commerce.cif.virtual-catalog is logged at all. Seems like it is stopping a step before trying to create it, but no error is showing up. Even response after binding seems good:

```
<html>
<head>
    <title>Content created /etc/commerce/products/roberty123</title>
</head>
    <body>
    <h1>Content created /etc/commerce/products/roberty123</h1>
    <table>
        <tbody>
            <tr>
                <td>Status</td>
                <td><div id="Status">201</div></td>
            </tr>
            <tr>
                <td>Message</td>
                <td><div id="Message">Created</div></td>
            </tr>
            <tr>
                <td>Location</td>
                <td><a href="/etc/commerce/products/roberty123" id="Location">/etc/commerce/products/roberty123</a></td>
            </tr>
            <tr>
                <td>Parent Location</td>
                <td><a href="/etc/commerce/products" id="ParentLocation">/etc/commerce/products</a></td>
            </tr>
            <tr>
                <td>Path</td>
                <td><div id="Path">/etc/commerce/products/roberty123</div></td>
            </tr>
            <tr>
                <td>Referer</td>
                <td><a href="http://<ofuscated url>/mnt/overlay/commerce/gui/content/products/bindproducttreewizard.html/etc/commerce/products/" id="Referer">http://<ofuscated url>/mnt/overlay/commerce/gui/content/products/bindproducttreewizard.html/etc/commerce/products/</a></td>
            </tr>
            <tr>
                <td>ChangeLog</td>
                <td><div id="ChangeLog">&lt;pre&gt;created(&quot;/etc/commerce/products/roberty123&quot;);&lt;br/&gt;deleted(&quot;/etc/commerce/products/roberty123/cq:catalogDataResourceProviderFactory&quot;);&lt;br/&gt;deleted(&quot;/etc/commerce/products/roberty123/jcr:language&quot;);&lt;br/&gt;modified(&quot;/etc/commerce/products/roberty123/jcr:title&quot;);&lt;br/&gt;modified(&quot;/etc/commerce/products/roberty123/cq:catalogDataResourceProviderFactory&quot;);&lt;br/&gt;modified(&quot;/etc/commerce/products/roberty123/cq:magentoStore&quot;);&lt;br/&gt;modified(&quot;/etc/commerce/products/roberty123/magentoRootCategoryId&quot;);&lt;br/&gt;modified(&quot;/etc/commerce/products/roberty123/cq:catalogIdentifier&quot;);&lt;br/&gt;&lt;/pre&gt;</div></td>
            </tr>
        </tbody>
    </table>
    <p><a href="http://<ofuscated url>/mnt/overlay/commerce/gui/content/products/bindproducttreewizard.html/etc/commerce/products/">Go Back</a></p>
    <p><a href="/etc/commerce/products/roberty123">Modified Resource</a></p>
    <p><a href="/
```
![Screenshot from 2019-08-29 15-26-55](https://user-images.githubusercontent.com/4612887/63966399-90be0c00-ca71-11e9-845f-013963494166.png)

About CRXDE (magento2, before creating roberty123):

![Screenshot from 2019-08-29 14-50-25](https://user-images.githubusercontent.com/4612887/63965726-2fe20400-ca70-11e9-8d4c-0fbe46fe4cec.png)
![Screenshot from 2019-08-29 14-50-46](https://user-images.githubusercontent.com/4612887/63965743-38d2d580-ca70-11e9-8390-f402d9ebb308.png)
![Screenshot from 2019-08-29 14-50-51](https://user-images.githubusercontent.com/4612887/63965753-3cfef300-ca70-11e9-91fd-de3740baf25d.png)

Bundle information (no virtual-catalog registered):
![Screenshot from 2019-08-29 15-14-21](https://user-images.githubusercontent.com/4612887/63965787-4d16d280-ca70-11e9-8669-b4dd56e84fb7.png)
![Screenshot from 2019-08-29 15-14-42](https://user-images.githubusercontent.com/4612887/63965794-4f792c80-ca70-11e9-9f38-c3e3498099ad.png)

**Comment by mhaack** [comment]
I don't think the JS errors are related, the problem is the missing resource provider service. But actually the config from your screenshots looks ok to me.

@LSantha do you have some idea?

**Comment by LSantha** [comment]
I've just built a stack with latest AEM 6.6 QS and latest archetype and it works as expected.
I recognize this is not AEM 6.4.4 as in the issue description, however one thing which looks odd to me is that the issue description contains everywhere references to /etc/commerce/products instead of /var/commerce/products. I wonder why is that? Why is that AEM 6.4.4 instance running in backwards compatibility mode? Also for AEM 6.4 the default product data location should be /var/commerce/products.

**Comment by robertymb** [comment]
Interesting question.

![Screenshot from 2019-09-02 08-34-17](https://user-images.githubusercontent.com/4612887/64112881-10dcbe00-cd5f-11e9-89b6-7cb21337e852.png)
_content from /etc/commerce/products/_

So, I reviewed what I had done and notice one slightly difference. Step 3 is different from this tutorial (that I have followed): https://www.adobe.io/apis/experiencecloud/commerce-integration-framework/getting-started.html (maybe need to update it?). In the getting started tutorial says to go to http://localhost:4502/aem/products.html/etc/commerce/products **(/etc)** but documentation tells to go to http://localhost:4502/aem/products.html/var/commerce/products **(/var)**.

That's probably why you saw /etc/commerce/products instead of /var/commerce/product. Good catch!

I tried to configure in /var instead of /etc. And it seems good! :) (thanks for the insight!) In case of anyone else faces this same issue, does you know what happened?

![Screenshot from 2019-09-02 08-34-43](https://user-images.githubusercontent.com/4612887/64112884-120deb00-cd5f-11e9-94ba-14af4b0bd2a3.png)
_content from /var/commerce/products/_

But after that, I tried to bind Product Teaser and it didn't show up the /var directory, just /etc directory :/ Just to let you know it seems good to Product Carousel (needs to test it but at least I can search for product SKU)

![Screenshot from 2019-09-02 08-55-15](https://user-images.githubusercontent.com/4612887/64113183-fbb45f00-cd5f-11e9-836b-1c8b8ed2c55e.png)
![Screenshot from 2019-09-02 08-55-05](https://user-images.githubusercontent.com/4612887/64113184-fbb45f00-cd5f-11e9-9045-8d373611e122.png)

Any idea or should I open a new issue to core component? I'll deep dive in the components before opening any issue regarding that (logs and stuffs).

I appreciate your help @mhaack and @LSantha.

**Comment by mhaack** [comment]
> Step 3 is different from this tutorial (that I have followed): https://www.adobe.io/apis/experiencecloud/commerce-integration-framework/getting-started.html (maybe need to update it?). 

Can you point is to the timestamp in the video when it mentions `/etc/commerce`?

**Comment by mhaack** [comment]
> But after that, I tried to bind Product Teaser and it didn't show up the /var directory, just /etc directory :/ Just to let you know it seems good to Product Carousel (needs to test it but at least I can search for product SKU)

Both components should not be different here?

**Comment by robertymb** [comment]
> > Step 3 is different from this tutorial (that I have followed): https://www.adobe.io/apis/experiencecloud/commerce-integration-framework/getting-started.html (maybe need to update it?).
> 
> Can you point is to the timestamp in the video when it mentions `/etc/commerce`?

7:55 when I click on **Products** it redirects me to /etc instead of /var (notice it's fine in the video)

**Comment by robertymb** [comment]
> > But after that, I tried to bind Product Teaser and it didn't show up the /var directory, just /etc directory :/ Just to let you know it seems good to Product Carousel (needs to test it but at least I can search for product SKU)
> 
> Both components should not be different here?

Yes, they are. I was expecting the behavior be exactly the same when searching for the product in both components.

**Comment by robertymb** [comment]
For some reason attribute `rootPath` from `cifconnector/src/main/content/jcr_root/libs/commerce/gui/components/common/cifproductfield/Initialize.java` was setting to `/etc/commerce/products` instead of `/var/commerce/products`. 

Noticed that for [core-cif-components/ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/_cq_dialog/.content.xml](https://github.com/adobe/aem-core-cif-components/blob/master/ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productteaser/v1/productteaser/_cq_dialog/.content.xml) don't have property `rootPath="/var/commerce/products"` but [core-cif-components/ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcarousel/v1/productcarousel/_cq_dialog/.content.xml](https://github.com/adobe/aem-core-cif-components/blob/master/ui.apps/src/main/content/jcr_root/apps/core/cif/components/commerce/productcarousel/v1/productcarousel/_cq_dialog/.content.xml) have it.

Not sure why it's not working on your environment and not on mine. But that's probably one fix. I'll propose this PR later for aem-core-components.

Thank you for you help so far.

Closing this issue.
