### ISSUE TITLE
Graphql client connection pool fills up

### ISSUE THREAD

**Issue by harts75** [adobe/commerce-cif-connector#48]
### Expected Behaviour
The connection pool should handle it's connections, and a timeout should be available
for when the graphql service is misbehaving

### Actual Behaviour
A timeout is not configurable for the graphql client. Connections will not timeout when stale.
And when a returned http status is != 200, the response is not consumed, this causes the connectionpool to flood.

### Reproduce Scenario (including but not limited to)
Let the graphql service return responses with status-code != 200. Connections will remain in connectionpool. When the pool is full, it will wait indefinitely for a connection to become available, locking the thread 

#### Steps to Reproduce
Setup the service to be in error state (e.g. return status 503)
Use the graphql client to do several calls. When the connection pool is full, it remains (default 20)
#### Platform and Version
AEM 6.4.5, graphql client 1.1.0

## Additional information
We are using the graphql client to fetch information from magento. 
And noticed the client to become unresponsive. A pull request will be available shortly, since we are dependant on the client to move on.

We are creating a pull request to address this issue with the client, as it is currently impeding our progress integrating magento. Is the timeout/connectionpool issue handled in a different way in the cif-components for magento?

**Comment by cjelger** [comment]
Thank you for reporting this issue, if this is indeed the case, then it's a very serious problem. Let us know when/if you can provide a PR, otherwise we will take care of it.

**Comment by harts75** [comment]
Hi Christophe,

Thanks.
This is the pull request:
https://github.com/adobe/commerce-cif-graphql-client/pull/9
I wanted to create a draft, but was too quick. I also wanted our tech-lead to check it out for improvements and code quality. This is my first pull request.

Best regards,
  Harmen Arts

**Comment by cjelger** [comment]
Is resolved by https://github.com/adobe/commerce-cif-connector/pull/49 - I'm closing this issue now. We'll release a new version of the connector in max 2-3 weeks (might be sooner).
