### ISSUE TITLE
Documentation for categoryRootId

### ISSUE THREAD

**Issue by solojavier** [adobe/commerce-cif-connector#6]
Currently there is a manual step that needs to be performed for categories to work, but it's not documented anywhere:

> Go to http://localhost:4502/crx/de/index.jsp#/content/venia/us/en/products/jcr%3Acontent there is `magentoRootCategoryId` property, that should be your Magento Default Category, same like used for binding.

**Comment by mhaack** [comment]
This issue should be logged in https://github.com/adobe/aem-core-cif-components project as it relates to the components and sample pages. The pages cannot use the config from the binding as there can be multiple bindings for multiple Magento store views and multiple pages using different Magento default categories.

**Comment by solojavier** [comment]
Done: https://github.com/adobe/aem-core-cif-components/issues/13
