### ISSUE TITLE
YUIScriptProcessor syntax error 

### ISSUE THREAD

**Issue by Jdruwe** [adobe/commerce-cif-connector#73]
### Expected Behaviour

No errors in the author error.log

### Actual Behaviour

`[ERROR] null
02.12.2019 10:19:02.036 *ERROR* [0:0:0:0:0:0:0:1 [1575278342019] GET /libs/commerce/gui/components/common/cifcategoryfield/clientlibs.min.js HTTP/1.1] com.adobe.granite.ui.clientlibs.impl.HtmlLibraryManagerImpl Error during assembly of library.
org.mozilla.javascript.EvaluatorException: Compilation produced 1 syntax errors.
	at com.adobe.granite.ui.clientlibs.impl.YUIScriptProcessor$1.runtimeError(YUIScriptProcessor.java:146) [com.adobe.granite.ui.clientlibs:1.0.76.CQ640-B0003]
	at org.mozilla.javascript.Parser.parse(Parser.java:396)
	at org.mozilla.javascript.Parser.parse(Parser.java:340)`

#### Steps to Reproduce

Enable minification under  'Adobe Granite HTML Library Manager'

<img width="455" alt="Screenshot 2019-12-02 at 10 20 45" src="https://user-images.githubusercontent.com/4804496/69947213-7b7fd000-14ed-11ea-9d33-a71e618f7850.png">

#### Platform and Version

Adobe Experience Manager (6.4.5.0) & connector 0.7.0

**Comment by LSantha** [comment]
@Jdruwe , thank you for reporting this. We are going to investigate it.
