### ISSUE TITLE
Virtual catalog config not picked up

### ISSUE THREAD

**Issue by Jdruwe** [adobe/commerce-cif-connector#74]
### Expected Behaviour

Virtual catalog configuration should be picked up correctly when  pushing it from code

### Actual Behaviour

Virtual catalog data definition is invalid (logs) and the integration stops working.

### Reproduce Scenario (including but not limited to)

Provide a GraphqlClientImpl and GraphqlDataServiceImpl config and push your product binding (in our case /var/commerce/products/magento-products using a META-INF filter. Restart the author, the binding is failing until you restart the virtual catalog bundle.

#### Platform and Version

Adobe Experience Manager (6.4.5.0) & connector 0.7.0

#### Images, code & logs that illustrates the problem

<img width="1001" alt="Screenshot 2019-12-02 at 09 45 55" src="https://user-images.githubusercontent.com/4804496/69947997-17f6a200-14ef-11ea-8474-415fffc973f2.png">
<img width="622" alt="Screenshot 2019-12-02 at 09 46 14" src="https://user-images.githubusercontent.com/4804496/69947999-17f6a200-14ef-11ea-8601-9d66db3c455d.png">

`com.adobe.cq.commerce.virtual.catalog.data.impl.CatalogDataResourceProviderManagerImpl Start registering all virtual catalog trees...
com.adobe.cq.commerce.virtual.catalog.data.impl.CatalogDataResourceProviderManagerImpl No factory found for provider id magento-graphql. Registering this data root will fail
om.adobe.cq.commerce.virtual.catalog.data.impl.CatalogDataResourceProviderManagerImpl Virtual catalog data definition at '/var/commerce/products/magento-products' is invalid.
com.adobe.cq.commerce.virtual.catalog.data.impl.CatalogDataResourceProviderManagerImpl Registered 0 virtual catalog data resource providers(s) in 4 ms, skipping 1 invalid one(s).
`

VIRTUAL CATALOG BUNDLE RESTART

`com.adobe.cq.commerce.virtual.catalog.data.impl.CatalogDataResourceProviderManagerImpl Start registering all virtual catalog trees...
com.adobe.cq.commerce.virtual.catalog.data.impl.CatalogDataResourceProviderManagerImpl Registered com.adobe.cq.commerce.graphql.resource.GraphqlResourceProvider@83e3337
com.adobe.cq.commerce.virtual.catalog.data.impl.CatalogDataResourceProviderManagerImpl Registered 1 virtual catalog data resource providers(s) in 10 ms, skipping 0 invalid one(s).
`

<img width="937" alt="Screenshot 2019-12-02 at 09 47 15" src="https://user-images.githubusercontent.com/4804496/69948000-188f3880-14ef-11ea-9d0a-ce1f4d02f00a.png">
<img width="684" alt="Screenshot 2019-12-02 at 09 47 25" src="https://user-images.githubusercontent.com/4804496/69948001-188f3880-14ef-11ea-9c9c-8b28aa621fdc.png">

_com.adobe.cq.commerce.graphql.client.impl.GraphqlClientImpl-magento-client.xml_

`<?xml version="1.0" encoding="UTF-8"?>
<jcr:root xmlns:sling="http://sling.apache.org/jcr/sling/1.0" xmlns:jcr="http://www.jcp.org/jcr/1.0"
          jcr:primaryType="sling:OsgiConfig"
          acceptSelfSignedCertificates="{Boolean}true"
          httpMethod="POST"
          identifier="magento-client"
          maxHttpConnections="{Decimal}20"
          url="https://127.0.0.1:443/graphql"
          socketTimeout="20000"/>
`

_com.adobe.cq.commerce.graphql.magento.GraphqlDataServiceImpl-magento-catalog.xml_

`<?xml version="1.0" encoding="UTF-8"?>
<jcr:root xmlns:sling="http://sling.apache.org/jcr/sling/1.0" xmlns:jcr="http://www.jcp.org/jcr/1.0"
          jcr:primaryType="sling:OsgiConfig"
          productCachingTimeMinutes="{Decimal}5"
          catalogCachingTimeMinutes="{Decimal}60"
          identifier="magento-client"
          categoryCachingSize="{Decimal}100"
          productCachingSize="{Decimal}1000"
          catalogCachingSchedulerEnabled="{Boolean}true"
          productCachingEnabled="{Boolean}true"
          catalogCachingEnabled="{Boolean}true"/>
`

_CIF Virtual Catalog - Bundlecom.adobe.commerce.cif.virtual-catalog_

`com.adobe.commerce.cif.connector-graphql bundle com.adobe.commerce.cif.connector-graphql:0.7.0 (585)[com.adobe.cq.commerce.graphql.magento.GraphqlDataServiceImpl(3858)] : The activate method has thrown an exception (java.lang.RuntimeException: Cannot find GraphqlClient with identifier 'magento-client')
java.lang.RuntimeException: Cannot find GraphqlClient with identifier 'magento-client'
	at com.adobe.cq.commerce.graphql.magento.GraphqlDataServiceImpl.activate(GraphqlDataServiceImpl.java:101) [com.adobe.commerce.cif.connector-graphql:0.7.0]`

**Comment by cjelger** [comment]
Thanks for reporting the issue. I think we indeed have a problem in the order in which services are started, we will try to fix this asap.

**Comment by cjelger** [comment]
PR is ready at #75

**Comment by cjelger** [comment]
Closed by #75
