### ISSUE TITLE
'CIF Catalog Magento GraphQL Configuration Factory' Not showing

### ISSUE THREAD

**Issue by diogoabferraz** [adobe/commerce-cif-connector#93]
### Expected Behaviour
After-mvn clean install -PautoInstall the 'CIF Catalog Magento GraphQL Configuration Factory' should appear in http://localhost:4502/system/console/configMgr

### Actual Behaviour
'CIF Catalog Magento GraphQL Configuration Factory'  not showing at http://localhost:4502/system/console/configMgr

#### Platform and Version
AEM 6.5
#### Logs taken while reproducing problem

**Comment by mhaack** [comment]
Can you check CIF connector related artifacts in package manager which packages are installed and in OSGI console which bundles are installed & started?

**Comment by mhaack** [comment]
Actually, you can get the ready to use package from: https://search.maven.org/search?q=g:com.adobe.commerce.cif%20AND%20a:cif-connector-all no need to build the project.

**Comment by diogo-celfocus** [comment]
Hi @mhaack ,

![image](https://user-images.githubusercontent.com/56916997/73742853-3e31fb80-4745-11ea-88fa-49802cfa6320.png)

I get this in the bundle.

**Comment by cjelger** [comment]
From the screenshot you added (and somehow then removed?), I think you have simply not installed the required dependencies, see https://github.com/adobe/commerce-cif-connector#pre-requisites

These are **not** automatically installed when you build and install all sub-modules. I'll update the documentation so it's clearly stated the first time that we mention `mvn clean install -PautoInstall`.

**Comment by diogo-celfocus** [comment]
Hi @cjelger @mhaack , the issue was the dependencies. I have installed all of them and it's working properly now. 

Thank You

**Comment by diogoabferraz** [comment]
Hi @cjelger @mhaack 

the issue was the dependencies hence not a issue. I have installed them and it works properly now.

Thank you

**Comment by diogoabferraz** [comment]
Closing
